total_cost_usd: 0.0019207549764944448
total_latency_sec: 26.83945977157829
cost_weight: 0.5
task_assignments:
  tweet_ingest:
    vmi_type: medium
    vmi_label: Medium VMI
    cpu: 1.94
    mem_gb: 0.68
    mode: stream
    namespace: speed-layer
    image: quay.io/kubevirt/cirros-container-disk-demo
  stream_classify:
    vmi_type: medium
    vmi_label: Medium VMI
    cpu: 1.46
    mem_gb: 0.64
    mode: stream
    namespace: speed-layer
    image: quay.io/kubevirt/cirros-container-disk-demo
  batch_retrain:
    vmi_type: large
    vmi_label: Large VMI
    cpu: 1.38
    mem_gb: 1.3
    mode: batch
    namespace: batch-layer
    image: quay.io/kubevirt/cirros-container-disk-demo
  result_store:
    vmi_type: small
    vmi_label: small VMI
    cpu: 1.0
    mem_gb: 0.5
    mode: serve
    namespace: serve-layer
    image: quay.io/kubevirt/cirros-container-disk-demo
  serving_api:
    vmi_type: medium
    vmi_label: Medium VMI
    cpu: 1.34
    mem_gb: 0.97
    mode: serve
    namespace: serve-layer
    image: quay.io/kubevirt/cirros-container-disk-demo
